version: '3.4'

networks:
    kidviz:
        external: false

services:
    db:
        build:
            context: .
            dockerfile: ../database/Dockerfile
        networks:
            kidviz: {}
        environment:
            POSTGRES_DB: kidviz
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
            PGDATA: /data
        volumes:
            - ./data:/data
        ports:
          - 5433:5432
    backend:
        build:
            context: ../..
            dockerfile: ./docker/development/Dockerfile
        networks:
            kidviz: {}
        environment:
            # Place any configuration options here.
            DATABASE_URL: postgres://postgres:secret@db:5432/kidviz
            DJANGO_EMAIL_BACKEND: anymail.backends.amazon_ses.EmailBackend
        env_file: env
        ports:
            - 8000:8000
        command: ['/tools/run.sh']
        volumes:
            - ../..:/app
